# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := download_closure
### Rules for action "download_closure":
quiet_cmd__usr_src_modpagespeed_net_instaweb_closure_gyp_download_closure_target_download_closure = ACTION _usr_src_modpagespeed_net_instaweb_closure_gyp_download_closure_target_download_closure $@
cmd__usr_src_modpagespeed_net_instaweb_closure_gyp_download_closure_target_download_closure = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd net/instaweb; mkdir -p ../../tools/closure; ../../third_party/closure/download.sh ../../tools/closure

tools/closure/compiler.jar: obj := $(abs_obj)
tools/closure/compiler.jar: builddir := $(abs_builddir)
tools/closure/compiler.jar: TOOLSET := $(TOOLSET)
tools/closure/compiler.jar: third_party/closure/download.sh FORCE_DO_CMD
	$(call do_cmd,_usr_src_modpagespeed_net_instaweb_closure_gyp_download_closure_target_download_closure)

all_deps += tools/closure/compiler.jar
action__usr_src_modpagespeed_net_instaweb_closure_gyp_download_closure_target_download_closure_outputs := tools/closure/compiler.jar


### Rules for final target.
# Build our special outputs first.
$(obj).target/net/instaweb/download_closure.stamp: | $(action__usr_src_modpagespeed_net_instaweb_closure_gyp_download_closure_target_download_closure_outputs)

# Preserve order dependency of special output on deps.
$(action__usr_src_modpagespeed_net_instaweb_closure_gyp_download_closure_target_download_closure_outputs): | 

$(obj).target/net/instaweb/download_closure.stamp: TOOLSET := $(TOOLSET)
$(obj).target/net/instaweb/download_closure.stamp:  FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/net/instaweb/download_closure.stamp
# Add target alias
.PHONY: download_closure
download_closure: $(obj).target/net/instaweb/download_closure.stamp

# Add target alias to "all" target.
.PHONY: all
all: download_closure

